config/routes.rb
Recycle::Application.routes.draw do

  root :to => 'home#index'
  match '/get_points' => 'home#get_points', :as => :get_points

end

app/models/recycle_point.rb
class RecyclePoint < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recycle_points = RecyclePoint.all
    
    respond_to do |format|
      format.html { render :html => @recycle_points }
    end
  end
  
  def get_points
    @all_recycle_points = RecyclePoint.all
    
    respond_to do |format|
      format.json { render :json => @all_recycle_points }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Recycle</title>
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<style type="text/css">
	  html { height: 100% }
	  body { font-family:arial; height: 100%; margin: 0; padding: 0; background-color:#333; }
	  #map_canvas { position:absolute; left:200px; right:10px; top:10px; bottom:10px; }
	  #sidebar { font-size:0.9em; width:200px;  background-color:#333; color:#F4F4F4;}
	  #sidebar-content { padding:10px; overflow:scroll; position:fixed; height:100%; }
	
		ul {
			list-style:none;
			width:180px;
			margin:0;
			padding:0;
		}
		
		ul a {
			display:block;
			color:#FFF;
			text-decoration:none;
			padding:10px;
			background-color:#444;
			border-bottom:3px solid #333;
		}
		
		ul a:hover {
			background-color:#555;
		}
		
		.heading {
			clear:both;
			font-weight:bold;
			display:block;
		}
	</style>
	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=true"></script>
	<script type="text/javascript">
		$(function() {
			// hook in with google API
			var latlng = new google.maps.LatLng(49.460817, -2.539000);
			var myOptions = {
				zoom: 12,
				center: latlng,
				mapTypeId: google.maps.MapTypeId.ROADMAP
		    };
			
		    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

			$.ajax({
				url: "<%= get_points_url %>",
				type: 'get',
				dataType: 'json',
				success: function(data) {
					$.each(data, function(index, recycle_point) {
						var point = new google.maps.LatLng(recycle_point.latitude, recycle_point.longitude);

						var marker = new google.maps.Marker({
						      position: point, 
						      map: map, 
						      title:"Hello World!"
						});
						
						createInfoWindow(map, marker, recycle_point);
					});
				},
				error: function() {
					alert("Noooo");
				}
			});
			
			/*
				INSERT INTO recycle_points(name, latitude, longitude) VALUES ("test", 49.454345, -2.604404);
				INSERT INTO recycle_points(name, latitude, longitude) VALUES ("test", 49.452336, -2.568526);
				INSERT INTO recycle_points(name, latitude, longitude) VALUES ("test", 49.460817, -2.539000);
			*/
		});
		
		function createInfoWindow(map, marker, recycle_point) {
			
			var infowindow = new google.maps.InfoWindow({
				content: createInfoWindowContent(recycle_point),
		        size: new google.maps.Size(50,50)
		    });
		  
			google.maps.event.addListener(marker, 'click', function() {
		    	infowindow.open(map, marker);
		  	});
		}
		
		function createInfoWindowContent(recycle_point) {
			return '<h3>' + recycle_point.name + '</h3><br /><br />' +
				recycle_point.description;
		}
	</script>
</head>
<body>

<%= yield %>

<div id="sidebar" style="width:200px">
	<div id="sidebar-content">
		<ul id="recycle_points">
			<% @recycle_points.each do |recycle_point| %>
				<li>
					<a href="#">
						<span class="picture">
							<%= image_tag(recycle_point.id.to_s + ".jpg")%>
						</span>
						<span class="heading">
							<%= recycle_point.name %>
						</span>
					
						<span class="description">
							<%= recycle_point.description %>
						</span>
					</a>
				</li>
			<% end %>
		</ul>
	</div>
</div>

<div id="map_canvas"></div>

</body>
</html>